# Docker Compose (v2)

version: "2"
services:
  web:
    image: webdevops/php-nginx:7.4
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "80:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homestead
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: webdevops/php:7.4
    working_dir: /app
    depends_on:
      - db
    user: application
    volumes:
      - ./:/app
    restart: on-failure
    entrypoint: [sh]
    command: [-c, "php artisan migrate"]

volumes:
  db_data:
